import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
        <Link href="/">HomePage</Link>
        <Link href="/postOne">Taking a Breath... How relaxing and stepping away helped me problem solve. </Link>
        <Link href="/postTwo">Post Two</Link>
        <Link href="/postThree">Post Three</Link>   
        </nav>
        {children}
      </body>
    </html>
  );
}
